/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteDevelopmentRouteImport } from './routes/website-development'
import { Route as UiUxDesignRouteImport } from './routes/ui-ux-design'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SoftwareDevelopmentRouteImport } from './routes/software-development'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SeoOptimizationRouteImport } from './routes/seo-optimization'
import { Route as ReactNativeDevelopmentRouteImport } from './routes/react-native-development'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MobileAppDevelopmentRouteImport } from './routes/mobile-app-development'
import { Route as ErpSolutionsRouteImport } from './routes/erp-solutions'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsViolinSriJaganPortfolioRouteImport } from './routes/projects.violin-sri-jagan-portfolio'
import { Route as ProjectsTrueluxeServiceRouteImport } from './routes/projects.trueluxe-service'
import { Route as ProjectsTrueluxeRouteImport } from './routes/projects.trueluxe'
import { Route as ProjectsSriKrishnaSupermarketRouteImport } from './routes/projects.sri-krishna-supermarket'
import { Route as ProjectsSriKrishnaDigitalWorldRouteImport } from './routes/projects.sri-krishna-digital-world'
import { Route as ProjectsSriKrishnaDigitalRouteImport } from './routes/projects.sri-krishna-digital'
import { Route as ProjectsMahaHostelRouteImport } from './routes/projects.maha-hostel'
import { Route as ProjectsLuminaTrustRouteImport } from './routes/projects.lumina-trust'
import { Route as ProjectsHaleemFxRouteImport } from './routes/projects.haleem-fx'
import { Route as ProjectsEbatAiDroneTechnologyRouteImport } from './routes/projects.ebat-ai-drone-technology'
import { Route as ProjectsCyberguardSecuritySuiteRouteImport } from './routes/projects.cyberguard-security-suite'
import { Route as ProjectsBsetTrustOrganizationRouteImport } from './routes/projects.bset-trust-organization'
import { Route as ProjectsAgsHealthyFoodsRouteImport } from './routes/projects.ags-healthy-foods'
import { Route as BlogWhySmallBusinessesNeedWebsitesRouteImport } from './routes/blog.why-small-businesses-need-websites'
import { Route as BlogWebsiteCostTamilNaduRouteImport } from './routes/blog.website-cost-tamil-nadu'
import { Route as BlogBenefitsOfCustomSoftwareRouteImport } from './routes/blog.benefits-of-custom-software'

const WebsiteDevelopmentRoute = WebsiteDevelopmentRouteImport.update({
  id: '/website-development',
  path: '/website-development',
  getParentRoute: () => rootRouteImport,
} as any)
const UiUxDesignRoute = UiUxDesignRouteImport.update({
  id: '/ui-ux-design',
  path: '/ui-ux-design',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareDevelopmentRoute = SoftwareDevelopmentRouteImport.update({
  id: '/software-development',
  path: '/software-development',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoOptimizationRoute = SeoOptimizationRouteImport.update({
  id: '/seo-optimization',
  path: '/seo-optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactNativeDevelopmentRoute = ReactNativeDevelopmentRouteImport.update({
  id: '/react-native-development',
  path: '/react-native-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppDevelopmentRoute = MobileAppDevelopmentRouteImport.update({
  id: '/mobile-app-development',
  path: '/mobile-app-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpSolutionsRoute = ErpSolutionsRouteImport.update({
  id: '/erp-solutions',
  path: '/erp-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsViolinSriJaganPortfolioRoute =
  ProjectsViolinSriJaganPortfolioRouteImport.update({
    id: '/projects/violin-sri-jagan-portfolio',
    path: '/projects/violin-sri-jagan-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsTrueluxeServiceRoute = ProjectsTrueluxeServiceRouteImport.update({
  id: '/projects/trueluxe-service',
  path: '/projects/trueluxe-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTrueluxeRoute = ProjectsTrueluxeRouteImport.update({
  id: '/projects/trueluxe',
  path: '/projects/trueluxe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSriKrishnaSupermarketRoute =
  ProjectsSriKrishnaSupermarketRouteImport.update({
    id: '/projects/sri-krishna-supermarket',
    path: '/projects/sri-krishna-supermarket',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsSriKrishnaDigitalWorldRoute =
  ProjectsSriKrishnaDigitalWorldRouteImport.update({
    id: '/projects/sri-krishna-digital-world',
    path: '/projects/sri-krishna-digital-world',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsSriKrishnaDigitalRoute =
  ProjectsSriKrishnaDigitalRouteImport.update({
    id: '/projects/sri-krishna-digital',
    path: '/projects/sri-krishna-digital',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsMahaHostelRoute = ProjectsMahaHostelRouteImport.update({
  id: '/projects/maha-hostel',
  path: '/projects/maha-hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLuminaTrustRoute = ProjectsLuminaTrustRouteImport.update({
  id: '/projects/lumina-trust',
  path: '/projects/lumina-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHaleemFxRoute = ProjectsHaleemFxRouteImport.update({
  id: '/projects/haleem-fx',
  path: '/projects/haleem-fx',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsEbatAiDroneTechnologyRoute =
  ProjectsEbatAiDroneTechnologyRouteImport.update({
    id: '/projects/ebat-ai-drone-technology',
    path: '/projects/ebat-ai-drone-technology',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsCyberguardSecuritySuiteRoute =
  ProjectsCyberguardSecuritySuiteRouteImport.update({
    id: '/projects/cyberguard-security-suite',
    path: '/projects/cyberguard-security-suite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsBsetTrustOrganizationRoute =
  ProjectsBsetTrustOrganizationRouteImport.update({
    id: '/projects/bset-trust-organization',
    path: '/projects/bset-trust-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsAgsHealthyFoodsRoute = ProjectsAgsHealthyFoodsRouteImport.update({
  id: '/projects/ags-healthy-foods',
  path: '/projects/ags-healthy-foods',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhySmallBusinessesNeedWebsitesRoute =
  BlogWhySmallBusinessesNeedWebsitesRouteImport.update({
    id: '/why-small-businesses-need-websites',
    path: '/why-small-businesses-need-websites',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogWebsiteCostTamilNaduRoute =
  BlogWebsiteCostTamilNaduRouteImport.update({
    id: '/website-cost-tamil-nadu',
    path: '/website-cost-tamil-nadu',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogBenefitsOfCustomSoftwareRoute =
  BlogBenefitsOfCustomSoftwareRouteImport.update({
    id: '/benefits-of-custom-software',
    path: '/benefits-of-custom-software',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/erp-solutions': typeof ErpSolutionsRoute
  '/mobile-app-development': typeof MobileAppDevelopmentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/project': typeof ProjectRoute
  '/react-native-development': typeof ReactNativeDevelopmentRoute
  '/seo-optimization': typeof SeoOptimizationRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/ui-ux-design': typeof UiUxDesignRoute
  '/website-development': typeof WebsiteDevelopmentRoute
  '/blog/benefits-of-custom-software': typeof BlogBenefitsOfCustomSoftwareRoute
  '/blog/website-cost-tamil-nadu': typeof BlogWebsiteCostTamilNaduRoute
  '/blog/why-small-businesses-need-websites': typeof BlogWhySmallBusinessesNeedWebsitesRoute
  '/projects/ags-healthy-foods': typeof ProjectsAgsHealthyFoodsRoute
  '/projects/bset-trust-organization': typeof ProjectsBsetTrustOrganizationRoute
  '/projects/cyberguard-security-suite': typeof ProjectsCyberguardSecuritySuiteRoute
  '/projects/ebat-ai-drone-technology': typeof ProjectsEbatAiDroneTechnologyRoute
  '/projects/haleem-fx': typeof ProjectsHaleemFxRoute
  '/projects/lumina-trust': typeof ProjectsLuminaTrustRoute
  '/projects/maha-hostel': typeof ProjectsMahaHostelRoute
  '/projects/sri-krishna-digital': typeof ProjectsSriKrishnaDigitalRoute
  '/projects/sri-krishna-digital-world': typeof ProjectsSriKrishnaDigitalWorldRoute
  '/projects/sri-krishna-supermarket': typeof ProjectsSriKrishnaSupermarketRoute
  '/projects/trueluxe': typeof ProjectsTrueluxeRoute
  '/projects/trueluxe-service': typeof ProjectsTrueluxeServiceRoute
  '/projects/violin-sri-jagan-portfolio': typeof ProjectsViolinSriJaganPortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/erp-solutions': typeof ErpSolutionsRoute
  '/mobile-app-development': typeof MobileAppDevelopmentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/project': typeof ProjectRoute
  '/react-native-development': typeof ReactNativeDevelopmentRoute
  '/seo-optimization': typeof SeoOptimizationRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/ui-ux-design': typeof UiUxDesignRoute
  '/website-development': typeof WebsiteDevelopmentRoute
  '/blog/benefits-of-custom-software': typeof BlogBenefitsOfCustomSoftwareRoute
  '/blog/website-cost-tamil-nadu': typeof BlogWebsiteCostTamilNaduRoute
  '/blog/why-small-businesses-need-websites': typeof BlogWhySmallBusinessesNeedWebsitesRoute
  '/projects/ags-healthy-foods': typeof ProjectsAgsHealthyFoodsRoute
  '/projects/bset-trust-organization': typeof ProjectsBsetTrustOrganizationRoute
  '/projects/cyberguard-security-suite': typeof ProjectsCyberguardSecuritySuiteRoute
  '/projects/ebat-ai-drone-technology': typeof ProjectsEbatAiDroneTechnologyRoute
  '/projects/haleem-fx': typeof ProjectsHaleemFxRoute
  '/projects/lumina-trust': typeof ProjectsLuminaTrustRoute
  '/projects/maha-hostel': typeof ProjectsMahaHostelRoute
  '/projects/sri-krishna-digital': typeof ProjectsSriKrishnaDigitalRoute
  '/projects/sri-krishna-digital-world': typeof ProjectsSriKrishnaDigitalWorldRoute
  '/projects/sri-krishna-supermarket': typeof ProjectsSriKrishnaSupermarketRoute
  '/projects/trueluxe': typeof ProjectsTrueluxeRoute
  '/projects/trueluxe-service': typeof ProjectsTrueluxeServiceRoute
  '/projects/violin-sri-jagan-portfolio': typeof ProjectsViolinSriJaganPortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/erp-solutions': typeof ErpSolutionsRoute
  '/mobile-app-development': typeof MobileAppDevelopmentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/project': typeof ProjectRoute
  '/react-native-development': typeof ReactNativeDevelopmentRoute
  '/seo-optimization': typeof SeoOptimizationRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/ui-ux-design': typeof UiUxDesignRoute
  '/website-development': typeof WebsiteDevelopmentRoute
  '/blog/benefits-of-custom-software': typeof BlogBenefitsOfCustomSoftwareRoute
  '/blog/website-cost-tamil-nadu': typeof BlogWebsiteCostTamilNaduRoute
  '/blog/why-small-businesses-need-websites': typeof BlogWhySmallBusinessesNeedWebsitesRoute
  '/projects/ags-healthy-foods': typeof ProjectsAgsHealthyFoodsRoute
  '/projects/bset-trust-organization': typeof ProjectsBsetTrustOrganizationRoute
  '/projects/cyberguard-security-suite': typeof ProjectsCyberguardSecuritySuiteRoute
  '/projects/ebat-ai-drone-technology': typeof ProjectsEbatAiDroneTechnologyRoute
  '/projects/haleem-fx': typeof ProjectsHaleemFxRoute
  '/projects/lumina-trust': typeof ProjectsLuminaTrustRoute
  '/projects/maha-hostel': typeof ProjectsMahaHostelRoute
  '/projects/sri-krishna-digital': typeof ProjectsSriKrishnaDigitalRoute
  '/projects/sri-krishna-digital-world': typeof ProjectsSriKrishnaDigitalWorldRoute
  '/projects/sri-krishna-supermarket': typeof ProjectsSriKrishnaSupermarketRoute
  '/projects/trueluxe': typeof ProjectsTrueluxeRoute
  '/projects/trueluxe-service': typeof ProjectsTrueluxeServiceRoute
  '/projects/violin-sri-jagan-portfolio': typeof ProjectsViolinSriJaganPortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookie-policy'
    | '/digital-marketing'
    | '/erp-solutions'
    | '/mobile-app-development'
    | '/privacy-policy'
    | '/project'
    | '/react-native-development'
    | '/seo-optimization'
    | '/service'
    | '/sitemap.xml'
    | '/software-development'
    | '/terms-and-conditions'
    | '/ui-ux-design'
    | '/website-development'
    | '/blog/benefits-of-custom-software'
    | '/blog/website-cost-tamil-nadu'
    | '/blog/why-small-businesses-need-websites'
    | '/projects/ags-healthy-foods'
    | '/projects/bset-trust-organization'
    | '/projects/cyberguard-security-suite'
    | '/projects/ebat-ai-drone-technology'
    | '/projects/haleem-fx'
    | '/projects/lumina-trust'
    | '/projects/maha-hostel'
    | '/projects/sri-krishna-digital'
    | '/projects/sri-krishna-digital-world'
    | '/projects/sri-krishna-supermarket'
    | '/projects/trueluxe'
    | '/projects/trueluxe-service'
    | '/projects/violin-sri-jagan-portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookie-policy'
    | '/digital-marketing'
    | '/erp-solutions'
    | '/mobile-app-development'
    | '/privacy-policy'
    | '/project'
    | '/react-native-development'
    | '/seo-optimization'
    | '/service'
    | '/sitemap.xml'
    | '/software-development'
    | '/terms-and-conditions'
    | '/ui-ux-design'
    | '/website-development'
    | '/blog/benefits-of-custom-software'
    | '/blog/website-cost-tamil-nadu'
    | '/blog/why-small-businesses-need-websites'
    | '/projects/ags-healthy-foods'
    | '/projects/bset-trust-organization'
    | '/projects/cyberguard-security-suite'
    | '/projects/ebat-ai-drone-technology'
    | '/projects/haleem-fx'
    | '/projects/lumina-trust'
    | '/projects/maha-hostel'
    | '/projects/sri-krishna-digital'
    | '/projects/sri-krishna-digital-world'
    | '/projects/sri-krishna-supermarket'
    | '/projects/trueluxe'
    | '/projects/trueluxe-service'
    | '/projects/violin-sri-jagan-portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookie-policy'
    | '/digital-marketing'
    | '/erp-solutions'
    | '/mobile-app-development'
    | '/privacy-policy'
    | '/project'
    | '/react-native-development'
    | '/seo-optimization'
    | '/service'
    | '/sitemap.xml'
    | '/software-development'
    | '/terms-and-conditions'
    | '/ui-ux-design'
    | '/website-development'
    | '/blog/benefits-of-custom-software'
    | '/blog/website-cost-tamil-nadu'
    | '/blog/why-small-businesses-need-websites'
    | '/projects/ags-healthy-foods'
    | '/projects/bset-trust-organization'
    | '/projects/cyberguard-security-suite'
    | '/projects/ebat-ai-drone-technology'
    | '/projects/haleem-fx'
    | '/projects/lumina-trust'
    | '/projects/maha-hostel'
    | '/projects/sri-krishna-digital'
    | '/projects/sri-krishna-digital-world'
    | '/projects/sri-krishna-supermarket'
    | '/projects/trueluxe'
    | '/projects/trueluxe-service'
    | '/projects/violin-sri-jagan-portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  ErpSolutionsRoute: typeof ErpSolutionsRoute
  MobileAppDevelopmentRoute: typeof MobileAppDevelopmentRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectRoute: typeof ProjectRoute
  ReactNativeDevelopmentRoute: typeof ReactNativeDevelopmentRoute
  SeoOptimizationRoute: typeof SeoOptimizationRoute
  ServiceRoute: typeof ServiceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoftwareDevelopmentRoute: typeof SoftwareDevelopmentRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UiUxDesignRoute: typeof UiUxDesignRoute
  WebsiteDevelopmentRoute: typeof WebsiteDevelopmentRoute
  ProjectsAgsHealthyFoodsRoute: typeof ProjectsAgsHealthyFoodsRoute
  ProjectsBsetTrustOrganizationRoute: typeof ProjectsBsetTrustOrganizationRoute
  ProjectsCyberguardSecuritySuiteRoute: typeof ProjectsCyberguardSecuritySuiteRoute
  ProjectsEbatAiDroneTechnologyRoute: typeof ProjectsEbatAiDroneTechnologyRoute
  ProjectsHaleemFxRoute: typeof ProjectsHaleemFxRoute
  ProjectsLuminaTrustRoute: typeof ProjectsLuminaTrustRoute
  ProjectsMahaHostelRoute: typeof ProjectsMahaHostelRoute
  ProjectsSriKrishnaDigitalRoute: typeof ProjectsSriKrishnaDigitalRoute
  ProjectsSriKrishnaDigitalWorldRoute: typeof ProjectsSriKrishnaDigitalWorldRoute
  ProjectsSriKrishnaSupermarketRoute: typeof ProjectsSriKrishnaSupermarketRoute
  ProjectsTrueluxeRoute: typeof ProjectsTrueluxeRoute
  ProjectsTrueluxeServiceRoute: typeof ProjectsTrueluxeServiceRoute
  ProjectsViolinSriJaganPortfolioRoute: typeof ProjectsViolinSriJaganPortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website-development': {
      id: '/website-development'
      path: '/website-development'
      fullPath: '/website-development'
      preLoaderRoute: typeof WebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-ux-design': {
      id: '/ui-ux-design'
      path: '/ui-ux-design'
      fullPath: '/ui-ux-design'
      preLoaderRoute: typeof UiUxDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-development': {
      id: '/software-development'
      path: '/software-development'
      fullPath: '/software-development'
      preLoaderRoute: typeof SoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-optimization': {
      id: '/seo-optimization'
      path: '/seo-optimization'
      fullPath: '/seo-optimization'
      preLoaderRoute: typeof SeoOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-native-development': {
      id: '/react-native-development'
      path: '/react-native-development'
      fullPath: '/react-native-development'
      preLoaderRoute: typeof ReactNativeDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app-development': {
      id: '/mobile-app-development'
      path: '/mobile-app-development'
      fullPath: '/mobile-app-development'
      preLoaderRoute: typeof MobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp-solutions': {
      id: '/erp-solutions'
      path: '/erp-solutions'
      fullPath: '/erp-solutions'
      preLoaderRoute: typeof ErpSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/violin-sri-jagan-portfolio': {
      id: '/projects/violin-sri-jagan-portfolio'
      path: '/projects/violin-sri-jagan-portfolio'
      fullPath: '/projects/violin-sri-jagan-portfolio'
      preLoaderRoute: typeof ProjectsViolinSriJaganPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/trueluxe-service': {
      id: '/projects/trueluxe-service'
      path: '/projects/trueluxe-service'
      fullPath: '/projects/trueluxe-service'
      preLoaderRoute: typeof ProjectsTrueluxeServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/trueluxe': {
      id: '/projects/trueluxe'
      path: '/projects/trueluxe'
      fullPath: '/projects/trueluxe'
      preLoaderRoute: typeof ProjectsTrueluxeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sri-krishna-supermarket': {
      id: '/projects/sri-krishna-supermarket'
      path: '/projects/sri-krishna-supermarket'
      fullPath: '/projects/sri-krishna-supermarket'
      preLoaderRoute: typeof ProjectsSriKrishnaSupermarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sri-krishna-digital-world': {
      id: '/projects/sri-krishna-digital-world'
      path: '/projects/sri-krishna-digital-world'
      fullPath: '/projects/sri-krishna-digital-world'
      preLoaderRoute: typeof ProjectsSriKrishnaDigitalWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sri-krishna-digital': {
      id: '/projects/sri-krishna-digital'
      path: '/projects/sri-krishna-digital'
      fullPath: '/projects/sri-krishna-digital'
      preLoaderRoute: typeof ProjectsSriKrishnaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/maha-hostel': {
      id: '/projects/maha-hostel'
      path: '/projects/maha-hostel'
      fullPath: '/projects/maha-hostel'
      preLoaderRoute: typeof ProjectsMahaHostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/lumina-trust': {
      id: '/projects/lumina-trust'
      path: '/projects/lumina-trust'
      fullPath: '/projects/lumina-trust'
      preLoaderRoute: typeof ProjectsLuminaTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/haleem-fx': {
      id: '/projects/haleem-fx'
      path: '/projects/haleem-fx'
      fullPath: '/projects/haleem-fx'
      preLoaderRoute: typeof ProjectsHaleemFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ebat-ai-drone-technology': {
      id: '/projects/ebat-ai-drone-technology'
      path: '/projects/ebat-ai-drone-technology'
      fullPath: '/projects/ebat-ai-drone-technology'
      preLoaderRoute: typeof ProjectsEbatAiDroneTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/cyberguard-security-suite': {
      id: '/projects/cyberguard-security-suite'
      path: '/projects/cyberguard-security-suite'
      fullPath: '/projects/cyberguard-security-suite'
      preLoaderRoute: typeof ProjectsCyberguardSecuritySuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/bset-trust-organization': {
      id: '/projects/bset-trust-organization'
      path: '/projects/bset-trust-organization'
      fullPath: '/projects/bset-trust-organization'
      preLoaderRoute: typeof ProjectsBsetTrustOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ags-healthy-foods': {
      id: '/projects/ags-healthy-foods'
      path: '/projects/ags-healthy-foods'
      fullPath: '/projects/ags-healthy-foods'
      preLoaderRoute: typeof ProjectsAgsHealthyFoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-small-businesses-need-websites': {
      id: '/blog/why-small-businesses-need-websites'
      path: '/why-small-businesses-need-websites'
      fullPath: '/blog/why-small-businesses-need-websites'
      preLoaderRoute: typeof BlogWhySmallBusinessesNeedWebsitesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/website-cost-tamil-nadu': {
      id: '/blog/website-cost-tamil-nadu'
      path: '/website-cost-tamil-nadu'
      fullPath: '/blog/website-cost-tamil-nadu'
      preLoaderRoute: typeof BlogWebsiteCostTamilNaduRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/benefits-of-custom-software': {
      id: '/blog/benefits-of-custom-software'
      path: '/benefits-of-custom-software'
      fullPath: '/blog/benefits-of-custom-software'
      preLoaderRoute: typeof BlogBenefitsOfCustomSoftwareRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogBenefitsOfCustomSoftwareRoute: typeof BlogBenefitsOfCustomSoftwareRoute
  BlogWebsiteCostTamilNaduRoute: typeof BlogWebsiteCostTamilNaduRoute
  BlogWhySmallBusinessesNeedWebsitesRoute: typeof BlogWhySmallBusinessesNeedWebsitesRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogBenefitsOfCustomSoftwareRoute: BlogBenefitsOfCustomSoftwareRoute,
  BlogWebsiteCostTamilNaduRoute: BlogWebsiteCostTamilNaduRoute,
  BlogWhySmallBusinessesNeedWebsitesRoute:
    BlogWhySmallBusinessesNeedWebsitesRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  ErpSolutionsRoute: ErpSolutionsRoute,
  MobileAppDevelopmentRoute: MobileAppDevelopmentRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectRoute: ProjectRoute,
  ReactNativeDevelopmentRoute: ReactNativeDevelopmentRoute,
  SeoOptimizationRoute: SeoOptimizationRoute,
  ServiceRoute: ServiceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoftwareDevelopmentRoute: SoftwareDevelopmentRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UiUxDesignRoute: UiUxDesignRoute,
  WebsiteDevelopmentRoute: WebsiteDevelopmentRoute,
  ProjectsAgsHealthyFoodsRoute: ProjectsAgsHealthyFoodsRoute,
  ProjectsBsetTrustOrganizationRoute: ProjectsBsetTrustOrganizationRoute,
  ProjectsCyberguardSecuritySuiteRoute: ProjectsCyberguardSecuritySuiteRoute,
  ProjectsEbatAiDroneTechnologyRoute: ProjectsEbatAiDroneTechnologyRoute,
  ProjectsHaleemFxRoute: ProjectsHaleemFxRoute,
  ProjectsLuminaTrustRoute: ProjectsLuminaTrustRoute,
  ProjectsMahaHostelRoute: ProjectsMahaHostelRoute,
  ProjectsSriKrishnaDigitalRoute: ProjectsSriKrishnaDigitalRoute,
  ProjectsSriKrishnaDigitalWorldRoute: ProjectsSriKrishnaDigitalWorldRoute,
  ProjectsSriKrishnaSupermarketRoute: ProjectsSriKrishnaSupermarketRoute,
  ProjectsTrueluxeRoute: ProjectsTrueluxeRoute,
  ProjectsTrueluxeServiceRoute: ProjectsTrueluxeServiceRoute,
  ProjectsViolinSriJaganPortfolioRoute: ProjectsViolinSriJaganPortfolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
